In [39]:
import tensorflow as tf
from transformers import TFAutoModelForSequenceClassification, BertTokenizer

In [40]:
import pandas as pd
import numpy as np
df = pd.read_table(
	'./train_snli.txt.zip',
	sep='\t',
	header=None,
	names=['text1', 'text2', 'label']
)

In [41]:
df.head()

text1  \
0  A person on a horse jumps over a broken down a...   
1  A person on a horse jumps over a broken down a...   
2              Children smiling and waving at camera   
3              Children smiling and waving at camera   
4  A boy is jumping on skateboard in the middle o...   

                                           text2  label  
0  A person is at a diner, ordering an omelette.      0  
1              A person is outdoors, on a horse.      1  
2                     There are children present      1  
3                          The kids are frowning      0  
4              The boy skates down the sidewalk.      0

In [42]:
# Split the data into train and test
# from sklearn.model_selection import train_test_split
# train, test = train_test_split(df, test_size=0.2, random_state=42)
train_df = df.sample(frac=0.8, random_state=42)
val_df = df.drop(train_df.index)

In [43]:
# Load BERT Tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [44]:
def tokenize_text(text1, text2):
	return tokenizer.encode_plus(
            text1, text2,
            add_special_tokens=True,
            max_length=64,
            padding='max_length',
            return_attention_mask=True,
            return_tensors='tf'
        )


In [61]:
tokenize_text(df.text1[0], df.text2[0]).items()

dict_items([('input_ids', <tf.Tensor: shape=(1, 64), dtype=int32, numpy=
array([[  101,  1037,  2711,  2006,  1037,  3586, 14523,  2058,  1037,
         3714,  2091, 13297,  1012,   102,  1037,  2711,  2003,  2012,
         1037, 15736,  1010, 13063,  2019, 18168, 12260,  4674,  1012,
          102,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0]], dtype=int32)>), ('token_type_ids', <tf.Tensor: shape=(1, 64), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>), ('attention_mask', <tf.Tensor: shape=(1, 64), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1,